export const DICE_BALANCE_LEDGER = Symbol('DICE_BALANCE_LEDGER');
export const DICE_HISTORY_REPOSITORY = Symbol('DICE_HISTORY_REPOSITORY');
export const USER_SEED_REPOSITORY = Symbol('USER_SEED_REPOSITORY');
export const DICE_BET_EVENT_PUBLISHER = Symbol('DICE_BET_EVENT_PUBLISHER');
