# Use Node 20 Alpine
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the app
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Expose port for dev
EXPOSE 3001

# Start the app in dev mode
CMD ["npm", "run", "start:dev"]
