export const CASE_REPOSITORY = Symbol('CASE_REPOSITORY');
export const CASE_LIST_CACHE = Symbol('CASE_LIST_CACHE');
export const CASE_LIST_FILTERED_READ = Symbol('CASE_LIST_FILTERED_READ');
export const CASE_DETAIL_CACHE = Symbol('CASE_DETAIL_CACHE');
export const CASE_BET_EVENT_PUBLISHER = Symbol('CASE_BET_EVENT_PUBLISHER');
