export const DAILY_SPIN_REPOSITORY = Symbol('DAILY_SPIN_REPOSITORY');
export const DAILY_SPIN_CACHE_PORT  = Symbol('DAILY_SPIN_CACHE_PORT');
export const DAILY_SPIN_BALANCE_PORT = Symbol('DAILY_SPIN_BALANCE_PORT');
