export const KINGUIN_CODE_REPOSITORY = Symbol('KINGUIN_CODE_REPOSITORY');
export const KINGUIN_BATCH_REPOSITORY = Symbol('KINGUIN_BATCH_REPOSITORY');
export const KINGUIN_REDEMPTION_LOG_REPOSITORY = Symbol('KINGUIN_REDEMPTION_LOG_REPOSITORY');
export const KINGUIN_BALANCE_PORT = Symbol('KINGUIN_BALANCE_PORT');
export const KINGUIN_CACHE_PORT = Symbol('KINGUIN_CACHE_PORT');
